/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main.Logic_root;

import Main.Conexion;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TheOneAboveAll
 */
public class JFShowUsers extends javax.swing.JFrame {

     
    Conexion conect = new Conexion();
    Connection con;
    Statement st;
    DefaultTableModel modeloOrdenes;
    ResultSet rs;
    
    /**
     * Creates new form JFShowUsers
     */
    public JFShowUsers() {
        initComponents();
        this.showUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsers = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBCreatePDF = new javax.swing.JButton();
        jBShowUsers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idUser", "Fecha de ultima actualizacion", "Ultima acción", "Ultima tabla actualizada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableUsers);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Usuarios Disponibles");

        jBCreatePDF.setText("Generar vitácora de acceso en archivo PDF");
        jBCreatePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCreatePDFActionPerformed(evt);
            }
        });

        jBShowUsers.setText("Mostrar usuarios");
        jBShowUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBShowUsersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBShowUsers))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 387, Short.MAX_VALUE)
                        .addComponent(jBCreatePDF)))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jBCreatePDF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBShowUsers)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showUsers(){
        for (int i = 0; i < this.jTableUsers.getRowCount(); i++){
            modeloOrdenes.removeRow(i);
            i = i - 1;
        }
        String sql1 = "select idUser, ultimaConeccion from users;";
       
        try{
            con = conect.getConnection();
            st = con.createStatement();
            rs= st.executeQuery(sql1);
            //rs2 = st.executeQuery(sql2);
            
            Object[] user = new Object[2];
            modeloOrdenes = (DefaultTableModel)this.jTableUsers.getModel();
            while(rs.next()){
                user[0] = rs.getInt("idUser");
                user[1] = rs.getString("ultimaConeccion");
                
                modeloOrdenes.addRow(user);  
               
            }
            this.jTableUsers.setModel(modeloOrdenes);
            
            
            
            //JOptionPane.showMessageDialog(null, "Registro exitoso a la base de datos");
            
        }catch(SQLException e){
            System.out.println(" El error es " + e);
        }
        
    
    }
    
    private void jBCreatePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCreatePDFActionPerformed
        // TODO add your handling code here:
        Document documento = new Document(PageSize.A4.rotate(), 10f, 10, 100f, 0f);
        try{
            String ruta = System.getProperty("user.home");
            String ruta1 = "/Downloads/VitacoraDeUsuarios.pdf";
            
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + ruta1));
            
            Paragraph titulo = new Paragraph();
            titulo.setAlignment(Paragraph.HEADER);
            titulo.setFont(FontFactory.getFont("Arial", 15, Font.ITALIC, BaseColor.BLACK));
            titulo.add("Vitacora de acceso");
            
            
            documento.open();
            documento.add(titulo);
            
            PdfPTable tabla = new PdfPTable(2);
            tabla.addCell("idUser");
            tabla.addCell("ultima Coneccion");
            
            for (int i = 0; i < this.jTableUsers.getRowCount(); i++){
            modeloOrdenes.removeRow(i);
            i = i - 1;
            }
            String sql1 = "select idUser, ultimaConeccion from users;";
            
            try{
                con = conect.getConnection();
                st = con.createStatement();
                rs= st.executeQuery(sql1);
                //rs2 = st.executeQuery(sql2);
            
         
                //modeloOrdenes = (DefaultTableModel)this.jTableUsers.getModel();
                while(rs.next()){
                    tabla.addCell(String.valueOf(rs.getInt("idUser")));
                    tabla.addCell(String.valueOf(rs.getString("ultimaConeccion")));
                    
                }
                //this.jTableUsers.setModel(modeloOrdenes);
              
            }catch(SQLException e){
                System.out.println(" El error es " + e);
            }
            documento.add(tabla);
            documento.close();
            JOptionPane.showMessageDialog(null, "Se guardó en la ruta " + ruta + ruta1);
        } catch (FileNotFoundException ex) {
                Logger.getLogger(JFShowUsers.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException e){
            System.out.println("El error es " + e);
            
        }
        //Date fechaD = new Date();
        
        //System.out.println("hoy es " + fechaD.toString());
        
        
        
        
    }//GEN-LAST:event_jBCreatePDFActionPerformed

    private void jBShowUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBShowUsersActionPerformed
        // TODO add your handling code here:
        
        
        this.showUsers();
    }//GEN-LAST:event_jBShowUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFShowUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFShowUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFShowUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFShowUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFShowUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCreatePDF;
    private javax.swing.JButton jBShowUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsers;
    // End of variables declaration//GEN-END:variables
}
