/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sitemacosteoporordenes.Prosesos;

import sitemacosteoporordenes.VentaPrincipal;
import org.apache.poi.xwpf.usermodel.*;
import javax.swing.*;
import java.io.FileOutputStream;
import java.io.IOException;

/**
 *
 * @author monfi
 */
public class VHojasDeCosto extends javax.swing.JFrame {

    /**
     * Creates new form VHojasDeCosto
     */
    public VHojasDeCosto() {
        initComponents();
    
    }
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPHojadeCostsos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTCliente = new javax.swing.JTextField();
        jTNumeroOrden = new javax.swing.JTextField();
        jTDescripcion = new javax.swing.JTextField();
        jTNumeroArticulos = new javax.swing.JTextField();
        jTFechaInicio = new javax.swing.JTextField();
        jTFechaTermino = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jBVolver = new javax.swing.JButton();
        jBResolver = new javax.swing.JButton();
        jBWord = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTFechaMD1 = new javax.swing.JTextField();
        jTFechaMD2 = new javax.swing.JTextField();
        jTNumeroRequisicionMD1 = new javax.swing.JTextField();
        jTNumeroRequisicionMD2 = new javax.swing.JTextField();
        jTCostoTotalMD1 = new javax.swing.JTextField();
        jTCostoTotalMD2 = new javax.swing.JTextField();
        jTFechaMO1 = new javax.swing.JTextField();
        jTFechaMO2 = new javax.swing.JTextField();
        jTHorasMO1 = new javax.swing.JTextField();
        jTHorasMO2 = new javax.swing.JTextField();
        jTTasaMO1 = new javax.swing.JTextField();
        jTTasaMO2 = new javax.swing.JTextField();
        jTCostoTotalMO1 = new javax.swing.JTextField();
        jTCostoTotalMO2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTNumeroOrdenGIF1 = new javax.swing.JTextField();
        jTNumeroOrdenGIF2 = new javax.swing.JTextField();
        jTHorasGIF1 = new javax.swing.JTextField();
        jTHorasGIF2 = new javax.swing.JTextField();
        jTTasaGIF1 = new javax.swing.JTextField();
        jTTasaGIF2 = new javax.swing.JTextField();
        jTCostoTotalGIF1 = new javax.swing.JTextField();
        jTCostoTotalGIF2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTMaterialesDirectos = new javax.swing.JTextField();
        jTManoDeObraDirecta = new javax.swing.JTextField();
        jTGastosIndirectosFabricacion = new javax.swing.JTextField();
        jTCostoTotal = new javax.swing.JTextField();
        jTCostoUnitario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPHojadeCostsos.setBackground(new java.awt.Color(255, 245, 225));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 30, 30));
        jLabel1.setText("Hoja de Costos");

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setText("Cliente:");

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 30, 30));
        jLabel3.setText("Numero de orden :");

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 30, 30));
        jLabel4.setText("Descripcion:");

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 30, 30));
        jLabel5.setText("No. articulos:");

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 30, 30));
        jLabel6.setText("Fecha de inicio:");

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 30, 30));
        jLabel7.setText("Fecha de termino:");

        jTCliente.setBackground(new java.awt.Color(255, 255, 255));
        jTCliente.setForeground(new java.awt.Color(30, 30, 30));
        jTCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTClienteActionPerformed(evt);
            }
        });

        jTNumeroOrden.setBackground(new java.awt.Color(255, 255, 255));
        jTNumeroOrden.setForeground(new java.awt.Color(30, 30, 30));

        jTDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        jTDescripcion.setForeground(new java.awt.Color(30, 30, 30));

        jTNumeroArticulos.setBackground(new java.awt.Color(255, 255, 255));
        jTNumeroArticulos.setForeground(new java.awt.Color(30, 30, 30));

        jTFechaInicio.setBackground(new java.awt.Color(255, 255, 255));
        jTFechaInicio.setForeground(new java.awt.Color(30, 30, 30));
        jTFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFechaInicioActionPerformed(evt);
            }
        });

        jTFechaTermino.setBackground(new java.awt.Color(255, 255, 255));
        jTFechaTermino.setForeground(new java.awt.Color(30, 30, 30));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(30, 30, 30));
        jLabel8.setText("Fecha MD");

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(30, 30, 30));
        jLabel9.setText("Numero de requisicion");

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(30, 30, 30));
        jLabel10.setText("Costo total MD");

        jLabel11.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(30, 30, 30));
        jLabel11.setText("Fecha MO");

        jLabel12.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(30, 30, 30));
        jLabel12.setText("Horas MO");

        jLabel13.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(30, 30, 30));
        jLabel13.setText("Tasa MO");

        jBVolver.setBackground(new java.awt.Color(139, 69, 19));
        jBVolver.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jBVolver.setForeground(new java.awt.Color(255, 255, 255));
        jBVolver.setText("Volver");
        jBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverActionPerformed(evt);
            }
        });

        jBResolver.setBackground(new java.awt.Color(234, 178, 102));
        jBResolver.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jBResolver.setForeground(new java.awt.Color(255, 255, 255));
        jBResolver.setText("Resolver");
        jBResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBResolverActionPerformed(evt);
            }
        });

        jBWord.setBackground(new java.awt.Color(195, 127, 61));
        jBWord.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jBWord.setForeground(new java.awt.Color(255, 255, 255));
        jBWord.setText("Word");
        jBWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBWordActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(30, 30, 30));
        jLabel15.setText("Costo Total MO");

        jLabel16.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(30, 30, 30));
        jLabel16.setText("Numero De Orden");

        jLabel17.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(30, 30, 30));
        jLabel17.setText("Horas GIF");

        jTFechaMD1.setBackground(new java.awt.Color(255, 255, 255));
        jTFechaMD1.setForeground(new java.awt.Color(30, 30, 30));

        jTFechaMD2.setBackground(new java.awt.Color(255, 255, 255));
        jTFechaMD2.setForeground(new java.awt.Color(30, 30, 30));

        jTNumeroRequisicionMD1.setBackground(new java.awt.Color(255, 255, 255));
        jTNumeroRequisicionMD1.setForeground(new java.awt.Color(30, 30, 30));

        jTNumeroRequisicionMD2.setBackground(new java.awt.Color(255, 255, 255));
        jTNumeroRequisicionMD2.setForeground(new java.awt.Color(30, 30, 30));

        jTCostoTotalMD1.setBackground(new java.awt.Color(255, 255, 255));
        jTCostoTotalMD1.setForeground(new java.awt.Color(30, 30, 30));
        jTCostoTotalMD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCostoTotalMD1ActionPerformed(evt);
            }
        });

        jTCostoTotalMD2.setBackground(new java.awt.Color(255, 255, 255));
        jTCostoTotalMD2.setForeground(new java.awt.Color(30, 30, 30));
        jTCostoTotalMD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCostoTotalMD2ActionPerformed(evt);
            }
        });

        jTFechaMO1.setBackground(new java.awt.Color(255, 255, 255));
        jTFechaMO1.setForeground(new java.awt.Color(30, 30, 30));

        jTFechaMO2.setBackground(new java.awt.Color(255, 255, 255));
        jTFechaMO2.setForeground(new java.awt.Color(30, 30, 30));

        jTHorasMO1.setBackground(new java.awt.Color(255, 255, 255));
        jTHorasMO1.setForeground(new java.awt.Color(30, 30, 30));

        jTHorasMO2.setBackground(new java.awt.Color(255, 255, 255));
        jTHorasMO2.setForeground(new java.awt.Color(30, 30, 30));
        jTHorasMO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTHorasMO2ActionPerformed(evt);
            }
        });

        jTTasaMO1.setBackground(new java.awt.Color(255, 255, 255));
        jTTasaMO1.setForeground(new java.awt.Color(30, 30, 30));
        jTTasaMO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTTasaMO1ActionPerformed(evt);
            }
        });

        jTTasaMO2.setBackground(new java.awt.Color(255, 255, 255));
        jTTasaMO2.setForeground(new java.awt.Color(30, 30, 30));

        jTCostoTotalMO1.setBackground(new java.awt.Color(255, 255, 255));
        jTCostoTotalMO1.setForeground(new java.awt.Color(30, 30, 30));

        jTCostoTotalMO2.setBackground(new java.awt.Color(255, 255, 255));
        jTCostoTotalMO2.setForeground(new java.awt.Color(30, 30, 30));

        jLabel18.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(30, 30, 30));
        jLabel18.setText("Tasa GIF");

        jLabel19.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(30, 30, 30));
        jLabel19.setText("Costo total GIF");

        jTNumeroOrdenGIF1.setBackground(new java.awt.Color(255, 255, 255));
        jTNumeroOrdenGIF1.setForeground(new java.awt.Color(30, 30, 30));

        jTNumeroOrdenGIF2.setBackground(new java.awt.Color(255, 255, 255));
        jTNumeroOrdenGIF2.setForeground(new java.awt.Color(30, 30, 30));

        jTHorasGIF1.setBackground(new java.awt.Color(255, 255, 255));
        jTHorasGIF1.setForeground(new java.awt.Color(30, 30, 30));

        jTHorasGIF2.setEditable(false);
        jTHorasGIF2.setBackground(new java.awt.Color(255, 255, 255));
        jTHorasGIF2.setForeground(new java.awt.Color(30, 30, 30));

        jTTasaGIF1.setBackground(new java.awt.Color(255, 255, 255));
        jTTasaGIF1.setForeground(new java.awt.Color(30, 30, 30));

        jTTasaGIF2.setBackground(new java.awt.Color(255, 255, 255));
        jTTasaGIF2.setForeground(new java.awt.Color(30, 30, 30));

        jTCostoTotalGIF1.setBackground(new java.awt.Color(255, 255, 255));
        jTCostoTotalGIF1.setForeground(new java.awt.Color(30, 30, 30));
        jTCostoTotalGIF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCostoTotalGIF1ActionPerformed(evt);
            }
        });

        jTCostoTotalGIF2.setBackground(new java.awt.Color(255, 255, 255));
        jTCostoTotalGIF2.setForeground(new java.awt.Color(30, 30, 30));

        jLabel20.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(30, 30, 30));
        jLabel20.setText("Materiales Directos");

        jLabel21.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(30, 30, 30));
        jLabel21.setText("Mano de Obra");

        jLabel22.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(30, 30, 30));
        jLabel22.setText("Gastos indirectos de fabricasion");

        jLabel14.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(30, 30, 30));
        jLabel14.setText("Materiales Directos General");

        jLabel23.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(30, 30, 30));
        jLabel23.setText("Mano de obra directa General");

        jLabel24.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(30, 30, 30));
        jLabel24.setText("Gastos indirectos de fabricacion General");

        jLabel25.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(30, 30, 30));
        jLabel25.setText("Costo Total General");

        jLabel26.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(30, 30, 30));
        jLabel26.setText("Costo Unitario General");

        jTMaterialesDirectos.setBackground(new java.awt.Color(255, 255, 255));
        jTMaterialesDirectos.setForeground(new java.awt.Color(30, 30, 30));

        jTManoDeObraDirecta.setBackground(new java.awt.Color(255, 255, 255));
        jTManoDeObraDirecta.setForeground(new java.awt.Color(30, 30, 30));

        jTGastosIndirectosFabricacion.setBackground(new java.awt.Color(255, 255, 255));
        jTGastosIndirectosFabricacion.setForeground(new java.awt.Color(30, 30, 30));
        jTGastosIndirectosFabricacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTGastosIndirectosFabricacionActionPerformed(evt);
            }
        });

        jTCostoTotal.setBackground(new java.awt.Color(255, 255, 255));
        jTCostoTotal.setForeground(new java.awt.Color(30, 30, 30));

        jTCostoUnitario.setBackground(new java.awt.Color(255, 255, 255));
        jTCostoUnitario.setForeground(new java.awt.Color(30, 30, 30));
        jTCostoUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCostoUnitarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPHojadeCostsosLayout = new javax.swing.GroupLayout(jPHojadeCostsos);
        jPHojadeCostsos.setLayout(jPHojadeCostsosLayout);
        jPHojadeCostsosLayout.setHorizontalGroup(
            jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPHojadeCostsosLayout.createSequentialGroup()
                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jTFechaMD1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFechaMD2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTNumeroOrden, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTDescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTNumeroArticulos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTFechaInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTFechaTermino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                                        .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTNumeroRequisicionMD1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBResolver)
                                            .addComponent(jTNumeroRequisicionMD2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(40, 40, 40)
                                        .addComponent(jBWord))))
                            .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel20))
                                .addGap(49, 49, 49)
                                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTCostoTotalMD1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTCostoTotalMD2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(79, 79, 79)
                                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFechaMO2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFechaMO1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))))
                    .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jBVolver)))
                .addGap(34, 34, 34)
                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPHojadeCostsosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addGap(364, 364, 364)
                        .addComponent(jLabel22)
                        .addGap(113, 113, 113))
                    .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                        .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTHorasMO2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTHorasMO1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTTasaMO1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTTasaMO2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTCostoTotalMO2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTCostoTotalMO1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)))
                            .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(jLabel23))
                            .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                                        .addGap(186, 186, 186)
                                        .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel25))
                                        .addGap(111, 111, 111))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPHojadeCostsosLayout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addGap(48, 48, 48)))
                                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTManoDeObraDirecta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTMaterialesDirectos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTGastosIndirectosFabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTCostoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                        .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(325, 325, 325)
                                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                                        .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTNumeroOrdenGIF1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTNumeroOrdenGIF2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTHorasGIF2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTHorasGIF1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12))
                                    .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)))
                                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTTasaGIF1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTTasaGIF2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)
                                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTCostoTotalGIF2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTCostoTotalGIF1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)))
                            .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(11, Short.MAX_VALUE))))
            .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                .addGap(564, 564, 564)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPHojadeCostsosLayout.setVerticalGroup(
            jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jTNumeroOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel23))
                        .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jTNumeroArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel25)))
                    .addGroup(jPHojadeCostsosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTMaterialesDirectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTManoDeObraDirecta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTGastosIndirectosFabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jTCostoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTFechaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFechaMD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNumeroRequisicionMD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCostoTotalMD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFechaMO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTHorasMO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTasaMO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCostoTotalMO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNumeroOrdenGIF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTHorasGIF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTasaGIF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCostoTotalGIF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFechaMD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNumeroRequisicionMD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCostoTotalMD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFechaMO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTHorasMO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTasaMO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCostoTotalMO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNumeroOrdenGIF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTHorasGIF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTasaGIF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCostoTotalGIF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPHojadeCostsosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBVolver)
                    .addComponent(jBResolver)
                    .addComponent(jBWord))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPHojadeCostsos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHojadeCostsos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBResolverActionPerformed
        // TODO add your handling code here:
        // Calcular los totales y el costo unitario
        calcularTotales();
    }//GEN-LAST:event_jBResolverActionPerformed

    private void calcularTotales() {
        double totalMaterialesDirectos = calcularTotal(jTCostoTotalMD1, jTCostoTotalMD2);
        jTMaterialesDirectos.setText(String.valueOf(totalMaterialesDirectos));

        double totalManoDeObra = calcularTotal(jTCostoTotalMO1, jTCostoTotalMO2);
        jTManoDeObraDirecta.setText(String.valueOf(totalManoDeObra));

        double totalGIF = calcularTotal(jTCostoTotalGIF1, jTCostoTotalGIF2);
        jTGastosIndirectosFabricacion.setText(String.valueOf(totalGIF));

        double costoTotalGeneral = totalMaterialesDirectos + totalManoDeObra + totalGIF;
        jTCostoTotal.setText(String.valueOf(costoTotalGeneral));

        try {
            double numeroArticulos = Double.parseDouble(jTNumeroArticulos.getText());
            double costoUnitarioGeneral = costoTotalGeneral / numeroArticulos;
            jTCostoUnitario.setText(String.valueOf(costoUnitarioGeneral));
        } catch (NumberFormatException e) {
            jTCostoUnitario.setText("0");
        }
    }

    private double calcularTotal(javax.swing.JTextField... fields) {
        double total = 0;
        for (javax.swing.JTextField field : fields) {
            try {
                total += Double.parseDouble(field.getText());
            } catch (NumberFormatException e) {
                total += 0;
            }
        }
        return total;
    }

    private void generarWord() {
        try {
            XWPFDocument document = new XWPFDocument();
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Guardar Word");
            int userSelection = fileChooser.showSaveDialog(this);
            if (userSelection == JFileChooser.APPROVE_OPTION) {
                FileOutputStream out = new FileOutputStream(fileChooser.getSelectedFile() + ".docx");

                // Añadir el título
                XWPFParagraph title = document.createParagraph();
                XWPFRun titleRun = title.createRun();
                titleRun.setText("Hoja de Costos");
                titleRun.setBold(true);
                titleRun.setFontSize(18);
                title.setAlignment(ParagraphAlignment.CENTER);

                // Añadir la información escalonada
                addParagraph(document, "Cliente: " + jTCliente.getText());
                addParagraph(document, "Número de Orden: " + jTNumeroOrden.getText());
                addParagraph(document, "Descripción: " + jTDescripcion.getText());
                addParagraph(document, "Número de Artículos: " + jTNumeroArticulos.getText());
                addParagraph(document, "Fecha de Inicio: " + jTFechaInicio.getText());
                addParagraph(document, "Fecha de Término: " + jTFechaTermino.getText());
                addParagraph(document, "");

                // Materiales Directos
                addParagraph(document, "Materiales Directos:");
                addParagraph(document, "Fecha MD: " + jTFechaMD1.getText() + ", Número de Requisición: " + jTNumeroRequisicionMD1.getText() + ", Costo Total MD: " + jTCostoTotalMD1.getText());
                addParagraph(document, "Fecha MD: " + jTFechaMD2.getText() + ", Número de Requisición: " + jTNumeroRequisicionMD2.getText() + ", Costo Total MD: " + jTCostoTotalMD2.getText());

                // Mano de Obra
                addParagraph(document, "Mano de Obra:");
                addParagraph(document, "Fecha MO: " + jTFechaMO1.getText() + ", Horas MO: " + jTHorasMO1.getText() + ", Tasa MO: " + jTTasaMO1.getText() + ", Costo Total MO: " + jTCostoTotalMO1.getText());
                addParagraph(document, "Fecha MO: " + jTFechaMO2.getText() + ", Horas MO: " + jTHorasMO2.getText() + ", Tasa MO: " + jTTasaMO2.getText() + ", Costo Total MO: " + jTCostoTotalMO2.getText());

                // Gastos Indirectos de Fabricación
                addParagraph(document, "Gastos Indirectos de Fabricación:");
                addParagraph(document, "Número de Orden: " + jTNumeroOrdenGIF1.getText() + ", Horas: " + jTHorasGIF1.getText() + ", Tasa: " + jTTasaGIF1.getText() + ", Costo Total GIF: " + jTCostoTotalGIF1.getText());
                addParagraph(document, "Número de Orden: " + jTNumeroOrdenGIF2.getText() + ", Horas: " + jTHorasGIF2.getText() + ", Tasa: " + jTTasaGIF2.getText() + ", Costo Total GIF: " + jTCostoTotalGIF2.getText());

                // Totales Generales
                addParagraph(document, "Materiales Directos General: " + jTMaterialesDirectos.getText());
                addParagraph(document, "Mano de Obra Directa General: " + jTManoDeObraDirecta.getText());
                addParagraph(document, "Gastos Indirectos de Fabricación General: " + jTGastosIndirectosFabricacion.getText());
                addParagraph(document, "Costo Total General: " + jTCostoTotal.getText());
                addParagraph(document, "Costo Unitario General: " + jTCostoUnitario.getText());

                document.write(out);
                out.close();
                JOptionPane.showMessageDialog(this, "Word generado exitosamente.");
            }
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al generar el archivo Word.");
        }
    }

    private void addParagraph(XWPFDocument document, String text) {
        XWPFParagraph paragraph = document.createParagraph();
        XWPFRun run = paragraph.createRun();
        run.setText(text);
    }
    
    private void jBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverActionPerformed
        // TODO add your handling code here:
        VentaPrincipal ventana = new VentaPrincipal();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBVolverActionPerformed

    private void jTFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFechaInicioActionPerformed

    private void jTCostoTotalMD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCostoTotalMD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCostoTotalMD1ActionPerformed

    private void jTCostoTotalMD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCostoTotalMD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCostoTotalMD2ActionPerformed

    private void jTGastosIndirectosFabricacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTGastosIndirectosFabricacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTGastosIndirectosFabricacionActionPerformed

    private void jTCostoUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCostoUnitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCostoUnitarioActionPerformed

    private void jTHorasMO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTHorasMO2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTHorasMO2ActionPerformed

    private void jTTasaMO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTasaMO1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTasaMO1ActionPerformed

    private void jTCostoTotalGIF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCostoTotalGIF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCostoTotalGIF1ActionPerformed

    private void jBWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBWordActionPerformed
        // TODO add your handling code here:
        // Generar Word con los datos
        generarWord();
    }//GEN-LAST:event_jBWordActionPerformed

    private void jTClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTClienteActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBResolver;
    private javax.swing.JButton jBVolver;
    private javax.swing.JButton jBWord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPHojadeCostsos;
    private javax.swing.JTextField jTCliente;
    private javax.swing.JTextField jTCostoTotal;
    private javax.swing.JTextField jTCostoTotalGIF1;
    private javax.swing.JTextField jTCostoTotalGIF2;
    private javax.swing.JTextField jTCostoTotalMD1;
    private javax.swing.JTextField jTCostoTotalMD2;
    private javax.swing.JTextField jTCostoTotalMO1;
    private javax.swing.JTextField jTCostoTotalMO2;
    private javax.swing.JTextField jTCostoUnitario;
    private javax.swing.JTextField jTDescripcion;
    private javax.swing.JTextField jTFechaInicio;
    private javax.swing.JTextField jTFechaMD1;
    private javax.swing.JTextField jTFechaMD2;
    private javax.swing.JTextField jTFechaMO1;
    private javax.swing.JTextField jTFechaMO2;
    private javax.swing.JTextField jTFechaTermino;
    private javax.swing.JTextField jTGastosIndirectosFabricacion;
    private javax.swing.JTextField jTHorasGIF1;
    private javax.swing.JTextField jTHorasGIF2;
    private javax.swing.JTextField jTHorasMO1;
    private javax.swing.JTextField jTHorasMO2;
    private javax.swing.JTextField jTManoDeObraDirecta;
    private javax.swing.JTextField jTMaterialesDirectos;
    private javax.swing.JTextField jTNumeroArticulos;
    private javax.swing.JTextField jTNumeroOrden;
    private javax.swing.JTextField jTNumeroOrdenGIF1;
    private javax.swing.JTextField jTNumeroOrdenGIF2;
    private javax.swing.JTextField jTNumeroRequisicionMD1;
    private javax.swing.JTextField jTNumeroRequisicionMD2;
    private javax.swing.JTextField jTTasaGIF1;
    private javax.swing.JTextField jTTasaGIF2;
    private javax.swing.JTextField jTTasaMO1;
    private javax.swing.JTextField jTTasaMO2;
    // End of variables declaration//GEN-END:variables
}
