/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sitemacosteoporordenes.Prosesos;

import sitemacosteoporordenes.VentaPrincipal;
import org.apache.poi.xwpf.usermodel.*;

import javax.swing.*;
import java.io.FileOutputStream;
import java.io.IOException;


/**
 *
 * @author monfi
 */
public class VResumenDeTargetasDeTiempo extends javax.swing.JFrame {

    /**
     * Creates new form VResumenDeTargetasDeTiempo
     */
    public VResumenDeTargetasDeTiempo() {
        initComponents();
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTNumeroOrden = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFecha1 = new javax.swing.JTextField();
        jTFecha2 = new javax.swing.JTextField();
        jTFecha3 = new javax.swing.JTextField();
        jTFecha4 = new javax.swing.JTextField();
        jTNumerohoras1 = new javax.swing.JTextField();
        jTNumerohoras2 = new javax.swing.JTextField();
        jTNumerohoras3 = new javax.swing.JTextField();
        jTNumerohoras4 = new javax.swing.JTextField();
        jTTasahora1 = new javax.swing.JTextField();
        jTTasahora2 = new javax.swing.JTextField();
        jTTasahora3 = new javax.swing.JTextField();
        jTTasahora4 = new javax.swing.JTextField();
        jTTotal1 = new javax.swing.JTextField();
        jTTotal2 = new javax.swing.JTextField();
        jTTotal3 = new javax.swing.JTextField();
        jTTotal4 = new javax.swing.JTextField();
        jBVolver = new javax.swing.JButton();
        jBResolver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBWord = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTTotalGeneral = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 245, 225));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 30, 30));
        jLabel1.setText("Resumen tarjetas de Tiempo");

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setText("Numero de orden:");

        jTNumeroOrden.setBackground(new java.awt.Color(255, 255, 255));
        jTNumeroOrden.setForeground(new java.awt.Color(30, 30, 30));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 30, 30));
        jLabel3.setText("Fecha");

        jTFecha1.setBackground(new java.awt.Color(255, 255, 255));
        jTFecha1.setForeground(new java.awt.Color(30, 30, 30));

        jTFecha2.setBackground(new java.awt.Color(255, 255, 255));
        jTFecha2.setForeground(new java.awt.Color(30, 30, 30));
        jTFecha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFecha2ActionPerformed(evt);
            }
        });

        jTFecha3.setBackground(new java.awt.Color(255, 255, 255));
        jTFecha3.setForeground(new java.awt.Color(30, 30, 30));

        jTFecha4.setEditable(false);
        jTFecha4.setBackground(new java.awt.Color(255, 255, 255));
        jTFecha4.setForeground(new java.awt.Color(30, 30, 30));
        jTFecha4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFecha4ActionPerformed(evt);
            }
        });

        jTNumerohoras1.setBackground(new java.awt.Color(255, 255, 255));
        jTNumerohoras1.setForeground(new java.awt.Color(30, 30, 30));

        jTNumerohoras2.setBackground(new java.awt.Color(255, 255, 255));
        jTNumerohoras2.setForeground(new java.awt.Color(30, 30, 30));

        jTNumerohoras3.setBackground(new java.awt.Color(255, 255, 255));
        jTNumerohoras3.setForeground(new java.awt.Color(30, 30, 30));
        jTNumerohoras3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNumerohoras3ActionPerformed(evt);
            }
        });

        jTNumerohoras4.setBackground(new java.awt.Color(255, 255, 255));
        jTNumerohoras4.setForeground(new java.awt.Color(30, 30, 30));

        jTTasahora1.setBackground(new java.awt.Color(255, 255, 255));
        jTTasahora1.setForeground(new java.awt.Color(30, 30, 30));

        jTTasahora2.setBackground(new java.awt.Color(255, 255, 255));
        jTTasahora2.setForeground(new java.awt.Color(30, 30, 30));

        jTTasahora3.setBackground(new java.awt.Color(255, 255, 255));
        jTTasahora3.setForeground(new java.awt.Color(30, 30, 30));

        jTTasahora4.setBackground(new java.awt.Color(255, 255, 255));
        jTTasahora4.setForeground(new java.awt.Color(30, 30, 30));

        jTTotal1.setBackground(new java.awt.Color(255, 255, 255));
        jTTotal1.setForeground(new java.awt.Color(30, 30, 30));
        jTTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTTotal1ActionPerformed(evt);
            }
        });

        jTTotal2.setBackground(new java.awt.Color(255, 255, 255));
        jTTotal2.setForeground(new java.awt.Color(30, 30, 30));

        jTTotal3.setBackground(new java.awt.Color(255, 255, 255));
        jTTotal3.setForeground(new java.awt.Color(30, 30, 30));

        jTTotal4.setEditable(false);
        jTTotal4.setBackground(new java.awt.Color(255, 255, 255));
        jTTotal4.setForeground(new java.awt.Color(30, 30, 30));
        jTTotal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTTotal4ActionPerformed(evt);
            }
        });

        jBVolver.setBackground(new java.awt.Color(139, 69, 19));
        jBVolver.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jBVolver.setForeground(new java.awt.Color(255, 255, 255));
        jBVolver.setText("Volver");
        jBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverActionPerformed(evt);
            }
        });

        jBResolver.setBackground(new java.awt.Color(234, 178, 102));
        jBResolver.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jBResolver.setForeground(new java.awt.Color(255, 255, 255));
        jBResolver.setText("Resolver");
        jBResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBResolverActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 30, 30));
        jLabel4.setText("Numero de horas");

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 30, 30));
        jLabel5.setText("Tarifa por hora");

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 30, 30));
        jLabel6.setText("Total");

        jBWord.setBackground(new java.awt.Color(195, 127, 61));
        jBWord.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jBWord.setForeground(new java.awt.Color(255, 255, 255));
        jBWord.setText("Word");
        jBWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBWordActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 30, 30));
        jLabel7.setText("Total");

        jTTotalGeneral.setBackground(new java.awt.Color(255, 255, 255));
        jTTotalGeneral.setForeground(new java.awt.Color(30, 30, 30));
        jTTotalGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTTotalGeneralActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTNumeroOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTTasahora4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTTasahora3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTTasahora2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTTasahora1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(145, 145, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTTotalGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFecha4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFecha3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNumerohoras3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNumerohoras4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNumerohoras2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNumerohoras1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTTotal4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)))
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBVolver)
                        .addGap(18, 18, 18)
                        .addComponent(jBResolver)
                        .addGap(32, 32, 32)
                        .addComponent(jBWord)
                        .addGap(34, 199, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTNumeroOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTTotalGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNumerohoras1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTasahora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNumerohoras2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTasahora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFecha3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNumerohoras3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTasahora3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFecha4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNumerohoras4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTasahora4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTotal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBVolver)
                    .addComponent(jBResolver)
                    .addComponent(jBWord))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverActionPerformed
        // TODO add your handling code here:
        VentaPrincipal ventana = new VentaPrincipal();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBVolverActionPerformed

    private void jTFecha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFecha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFecha2ActionPerformed

    private void jTNumerohoras3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNumerohoras3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNumerohoras3ActionPerformed

    private void jTFecha4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFecha4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFecha4ActionPerformed

    private void jTTotal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTotal4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTotal4ActionPerformed

    private void jBResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBResolverActionPerformed
        // TODO add your handling code here:
         // Calcular el Total por cada fila y el Total General
        calcularTotales();
    }//GEN-LAST:event_jBResolverActionPerformed

    private void calcularTotales() {
        calcularTotalFila(jTNumerohoras1, jTTasahora1, jTTotal1);
        calcularTotalFila(jTNumerohoras2, jTTasahora2, jTTotal2);
        calcularTotalFila(jTNumerohoras3, jTTasahora3, jTTotal3);
        calcularTotalFila(jTNumerohoras4, jTTasahora4, jTTotal4);

        double totalGeneral = calcularTotalGeneral();
        jTTotalGeneral.setText(String.valueOf(totalGeneral));
    }

    private void calcularTotalFila(javax.swing.JTextField jTNumerohoras, javax.swing.JTextField jTTasahora, javax.swing.JTextField jTTotal) {
        try {
            double horas = Double.parseDouble(jTNumerohoras.getText());
            double tarifa = Double.parseDouble(jTTasahora.getText());
            double total = horas * tarifa;
            jTTotal.setText(String.valueOf(total));
        } catch (NumberFormatException e) {
            jTTotal.setText("0");
        }
    }

    private double calcularTotalGeneral() {
        double total1 = obtenerValor(jTTotal1);
        double total2 = obtenerValor(jTTotal2);
        double total3 = obtenerValor(jTTotal3);
        double total4 = obtenerValor(jTTotal4);
        return total1 + total2 + total3 + total4;
    }

    private double obtenerValor(javax.swing.JTextField jTTotal) {
        try {
            return Double.parseDouble(jTTotal.getText());
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    private void generarWord() {
        try {
            XWPFDocument document = new XWPFDocument();
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Guardar Word");
            int userSelection = fileChooser.showSaveDialog(this);
            if (userSelection == JFileChooser.APPROVE_OPTION) {
                FileOutputStream out = new FileOutputStream(fileChooser.getSelectedFile() + ".docx");

                // Añadir el título
                XWPFParagraph title = document.createParagraph();
                XWPFRun titleRun = title.createRun();
                titleRun.setText("Tarjetas de Tiempo de Trabajadores");
                titleRun.setBold(true);
                titleRun.setFontSize(18);
                title.setAlignment(ParagraphAlignment.CENTER);

                // Añadir la información escalonada
                addParagraph(document, "Número de Orden: " + jTNumeroOrden.getText());
                addParagraph(document, "Total: " + jTTotalGeneral.getText());
                addParagraph(document, "");

                addParagraph(document, "Fecha: " + jTFecha1.getText() + " - Número de Horas: " + jTNumerohoras1.getText() + " - Tarifa por Hora: " + jTTasahora1.getText() + " - Total: " + jTTotal1.getText());
                addParagraph(document, "Fecha: " + jTFecha2.getText() + " - Número de Horas: " + jTNumerohoras2.getText() + " - Tarifa por Hora: " + jTTasahora2.getText() + " - Total: " + jTTotal2.getText());
                addParagraph(document, "Fecha: " + jTFecha3.getText() + " - Número de Horas: " + jTNumerohoras3.getText() + " - Tarifa por Hora: " + jTTasahora3.getText() + " - Total: " + jTTotal3.getText());
                addParagraph(document, "Fecha: " + jTFecha4.getText() + " - Número de Horas: " + jTNumerohoras4.getText() + " - Tarifa por Hora: " + jTTasahora4.getText() + " - Total: " + jTTotal4.getText());

                document.write(out);
                out.close();
                JOptionPane.showMessageDialog(this, "Word generado exitosamente.");
            }
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al generar el archivo Word.");
        }
    }

    private void addParagraph(XWPFDocument document, String text) {
        XWPFParagraph paragraph = document.createParagraph();
        XWPFRun run = paragraph.createRun();
        run.setText(text);
    }
    
    private void jBWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBWordActionPerformed
        // TODO add your handling code here:
         // Generar Word con los datos
        generarWord();
    }//GEN-LAST:event_jBWordActionPerformed

    private void jTTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTotal1ActionPerformed

    private void jTTotalGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTotalGeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTotalGeneralActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBResolver;
    private javax.swing.JButton jBVolver;
    private javax.swing.JButton jBWord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFecha1;
    private javax.swing.JTextField jTFecha2;
    private javax.swing.JTextField jTFecha3;
    private javax.swing.JTextField jTFecha4;
    private javax.swing.JTextField jTNumeroOrden;
    private javax.swing.JTextField jTNumerohoras1;
    private javax.swing.JTextField jTNumerohoras2;
    private javax.swing.JTextField jTNumerohoras3;
    private javax.swing.JTextField jTNumerohoras4;
    private javax.swing.JTextField jTTasahora1;
    private javax.swing.JTextField jTTasahora2;
    private javax.swing.JTextField jTTasahora3;
    private javax.swing.JTextField jTTasahora4;
    private javax.swing.JTextField jTTotal1;
    private javax.swing.JTextField jTTotal2;
    private javax.swing.JTextField jTTotal3;
    private javax.swing.JTextField jTTotal4;
    private javax.swing.JTextField jTTotalGeneral;
    // End of variables declaration//GEN-END:variables
}
