/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.sql.Connection;
import java.sql.Statement;

/**
 *
 * @author TheOneAboveAll
 */
public class RequisicionM extends javax.swing.JFrame {
    ConeccionBaseDeDatos conect = new ConeccionBaseDeDatos();
    Statement statement;
    public double total;
    
    Connection coneccion;
    /**
     * Creates new form RequisicionM
     */
    public RequisicionM() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomRe = new javax.swing.JTextField();
        nomDepa = new javax.swing.JTextField();
        noOrden = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Tot = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cant2 = new javax.swing.JTextField();
        cant1 = new javax.swing.JTextField();
        calcular = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cm1 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        l2 = new javax.swing.JCheckBox();
        m2 = new javax.swing.JCheckBox();
        ml1 = new javax.swing.JCheckBox();
        m31 = new javax.swing.JCheckBox();
        m21 = new javax.swing.JCheckBox();
        kg1 = new javax.swing.JCheckBox();
        m1 = new javax.swing.JCheckBox();
        cm2 = new javax.swing.JCheckBox();
        l1 = new javax.swing.JCheckBox();
        ml2 = new javax.swing.JCheckBox();
        m22 = new javax.swing.JCheckBox();
        m32 = new javax.swing.JCheckBox();
        kg2 = new javax.swing.JCheckBox();
        g2 = new javax.swing.JCheckBox();
        g1 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        costoU2 = new javax.swing.JTextField();
        descripcion2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        costoTot1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        costoTot2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        descripcion1 = new javax.swing.JTextField();
        costoU1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Requisición de materiales");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(554, 554, 554)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setText("Número de requisicion:");

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 30, 30));
        jLabel3.setText("Departamento:");

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 30, 30));
        jLabel4.setText("Número de Orden:");

        nomRe.setBackground(new java.awt.Color(255, 255, 255));
        nomRe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomRe.setForeground(new java.awt.Color(0, 0, 0));
        nomRe.setMinimumSize(new java.awt.Dimension(100, 35));

        nomDepa.setBackground(new java.awt.Color(255, 255, 255));
        nomDepa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomDepa.setForeground(new java.awt.Color(0, 0, 0));
        nomDepa.setMinimumSize(new java.awt.Dimension(100, 35));

        noOrden.setBackground(new java.awt.Color(255, 255, 255));
        noOrden.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        noOrden.setForeground(new java.awt.Color(0, 0, 0));
        noOrden.setMinimumSize(new java.awt.Dimension(100, 35));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 30, 30));
        jLabel5.setText("Fecha:");

        fecha.setBackground(new java.awt.Color(255, 255, 255));
        fecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fecha.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(30, 30, 30));
        jLabel8.setText("Total:");

        Tot.setBackground(new java.awt.Color(255, 255, 255));
        Tot.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tot.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(30, 30, 30));
        jLabel10.setText("Cantidad");

        cant2.setBackground(new java.awt.Color(255, 255, 255));
        cant2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cant2.setForeground(new java.awt.Color(0, 0, 0));
        cant2.setMinimumSize(new java.awt.Dimension(90, 34));

        cant1.setBackground(new java.awt.Color(255, 255, 255));
        cant1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cant1.setForeground(new java.awt.Color(0, 0, 0));
        cant1.setMinimumSize(new java.awt.Dimension(90, 34));
        cant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cant1ActionPerformed(evt);
            }
        });

        calcular.setText("Calcular ");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cm1.setForeground(new java.awt.Color(0, 0, 0));
        cm1.setText("Cm");

        jLabel13.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(30, 30, 30));
        jLabel13.setText("Unidad de medida");

        l2.setForeground(new java.awt.Color(0, 0, 0));
        l2.setText("Lts");

        m2.setForeground(new java.awt.Color(0, 0, 0));
        m2.setText("M");

        ml1.setForeground(new java.awt.Color(0, 0, 0));
        ml1.setText("ml");

        m31.setForeground(new java.awt.Color(0, 0, 0));
        m31.setText("M^3");

        m21.setForeground(new java.awt.Color(0, 0, 0));
        m21.setText("M^2");

        kg1.setForeground(new java.awt.Color(0, 0, 0));
        kg1.setText("Kg");

        m1.setForeground(new java.awt.Color(0, 0, 0));
        m1.setText("M");

        cm2.setForeground(new java.awt.Color(0, 0, 0));
        cm2.setText("Cm");

        l1.setForeground(new java.awt.Color(0, 0, 0));
        l1.setText("Lts");

        ml2.setForeground(new java.awt.Color(0, 0, 0));
        ml2.setText("ml");

        m22.setForeground(new java.awt.Color(0, 0, 0));
        m22.setText("M^2");

        m32.setForeground(new java.awt.Color(0, 0, 0));
        m32.setText("M^3");

        kg2.setForeground(new java.awt.Color(0, 0, 0));
        kg2.setText("Kg");

        g2.setForeground(new java.awt.Color(0, 0, 0));
        g2.setText("G");

        g1.setForeground(new java.awt.Color(0, 0, 0));
        g1.setText("G");

        jCheckBox9.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox9.setText("Unidades");

        jCheckBox18.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox18.setText("Unidades");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(calcular)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cant1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(cant2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(m1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cm1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ml1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kg1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(g1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cm2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ml2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(m32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kg2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(g2)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox18))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cant1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ml1)
                    .addComponent(m21)
                    .addComponent(cm1)
                    .addComponent(m31)
                    .addComponent(kg1)
                    .addComponent(m1)
                    .addComponent(l1)
                    .addComponent(g1)
                    .addComponent(jCheckBox9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cant2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m2)
                    .addComponent(cm2)
                    .addComponent(l2)
                    .addComponent(ml2)
                    .addComponent(m22)
                    .addComponent(m32)
                    .addComponent(kg2)
                    .addComponent(g2)
                    .addComponent(jCheckBox18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcular)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(47, 47, 47))
        );

        costoU2.setBackground(new java.awt.Color(255, 255, 255));
        costoU2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        costoU2.setForeground(new java.awt.Color(0, 0, 0));

        descripcion2.setBackground(new java.awt.Color(255, 255, 255));
        descripcion2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descripcion2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel15.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(30, 30, 30));
        jLabel15.setText("Costo total");

        costoTot1.setBackground(new java.awt.Color(255, 255, 255));
        costoTot1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        costoTot1.setForeground(new java.awt.Color(0, 0, 0));
        costoTot1.setText("0.00");

        jLabel11.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(30, 30, 30));
        jLabel11.setText("Descripción del material");

        costoTot2.setBackground(new java.awt.Color(255, 255, 255));
        costoTot2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        costoTot2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel12.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(30, 30, 30));
        jLabel12.setText("Costo unitario");

        descripcion1.setBackground(new java.awt.Color(255, 255, 255));
        descripcion1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descripcion1.setForeground(new java.awt.Color(0, 0, 0));

        costoU1.setBackground(new java.awt.Color(255, 255, 255));
        costoU1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        costoU1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(nomRe, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(nomDepa, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tot, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(noOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(descripcion2)
                            .addComponent(descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(costoU1)
                                    .addComponent(costoU2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(costoTot1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(costoTot2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(165, 165, 165)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomRe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(noOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomDepa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(Tot, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costoU1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costoTot1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costoU2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costoTot2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        int c1 = Integer.parseInt(cant1.getText()); //cantidad de cada material
        int c2 = 0;
        
        double cu1; //costo unitario de cada material
        double cu2 = 0;
        double ct1; // costos totales
        double ct2 = 0;
        
        if( cant2.getText().isEmpty() && costoU2.getText().isEmpty() && costoTot2.getText().isEmpty()){
            ct2 = 0;
            costoTot2.setText(ct2 + "");
            
        } else if( ! costoTot2.getText().isEmpty()){
            ct2 = Double.parseDouble(costoTot2.getText());
            
        } else {
            c2 = Integer.parseInt(this.cant2.getText()); 
            String descripcion2 = this.descripcion2.getText();
            
            if (costoU2.getText().isEmpty()){
                //Se analisa si no existe el costo unitario y se calcula
                ct2 = Double.parseDouble(costoTot2.getText());
                cu2 = ct2 / c2;
                costoU2.setText(cu2 + ""); 
                
            } else { cu2 = Double.parseDouble(costoU2.getText());}
            
            ct2 = c2 * cu2;
            costoTot2.setText(ct2 + "");
        }
        
        System.out.println("Todo bien 1");
        //todo bien
        
        
        if(costoU1.getText().isEmpty()){
            //Se analisa si no existe el costo unitario y se calcula
            ct1 = Double.parseDouble(costoTot1.getText());
            cu1 = ct1 / c1;
            costoU1.setText(cu1 + "");
            
        } else{ cu1 = Double.parseDouble(costoU1.getText()); }
        
        
        System.out.println("todo bien 3");
        
        ct1 = c1 * cu1; //calculo de los costos totales
        
        costoTot1.setText(ct1 + ""); //Se colocan los cotos totales
        
        
        String numeroRe = nomRe.getText();  //Se guardan los datos de la requisicion
        String depa = nomDepa.getText();
        String noOrden = this.noOrden.getText();
        
        
        String fechaD = fecha.getText();
       
        System.out.println("todo bien 4");
        total = ct1 + ct2;
        
        Tot.setText(total + "");
       
        
    }//GEN-LAST:event_calcularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double tot2 = Double.parseDouble(costoTot2.getText());
        
        String noR = nomRe.getText(); //se guardan los datos de la requisicion
        String d = nomDepa.getText();
        String noO = noOrden.getText();
        String tot = Tot.getText();
        String f = fecha.getText();
        
        int c1 = Integer.parseInt(cant1.getText()); //Se guardan datos del primer material
        String d1 = descripcion1.getText();
        double cu1 = Double.parseDouble(costoU1.getText());
        double ct1 = Double.parseDouble(costoTot1.getText());
        
        String c2;
        String d2;
        String cu2;
        //Si no hubo un 2do material se dejan nullos los valores 
        if(tot2 == 0){
            c2 = "null";
            d2 = "null";
            cu2 = "null";
            
        } else {
           if(cant2.getText().isEmpty()){  c2 = "null";     } else {  c2 = cant2.getText();   }
           
           if(costoU2.getText().isEmpty()){    cu2 = "null";    } else {    cu2 = costoU2.getText();    }
          
           if(descripcion2.getText().isEmpty()){    d2 = "null";    } else {    d2 = descripcion2.getText();       }
            
        } 
        String sql;
        String unidad1 = "", unidad2 = "";
        if(m1.isSelected()){    unidad1 = c1 + " metros ";
        } if(m2.isSelected()){    unidad2 = c2 + " metros ";
        } if(cm1.isSelected()){    unidad1 =c1 + " centimetros ";
        } if(cm2.isSelected()){    unidad2 = c2 + " centimetros ";
        } if(l1.isSelected()){    unidad1 =c1 + " litros ";
        } if(l2.isSelected()){    unidad2 =c2 + " litros ";
        } if(ml1.isSelected()){    unidad1 =c1 + " mililitros ";
        } if(ml2.isSelected()){    unidad2 =c2 + " mililitro ";
        } if(m21.isSelected()){    unidad1 =c1 + " metros cuadrados ";
        } if(m22.isSelected()){    unidad2 =c2 + " metros cuadrados ";
        } if(m31.isSelected()){    unidad1 =c1 + " metros cubicos ";
        } if(m32.isSelected()){    unidad2 =c2 + " metros cubicos ";
        } if(kg1.isSelected()){    unidad1 =c1 + " kilogramos ";
        } if(kg2.isSelected()){    unidad2 =c2 + " kilogramos ";
        } if(g1.isSelected()){    unidad1 =c1 + " gramos ";
        } if(g2.isSelected()){    unidad2 =c2 + " gramos ";
        } if(g1.isSelected()){    unidad1 =c1 + " gramos ";
        } if(g2.isSelected()){    unidad2 =c2 + " gramos ";
        }
        
        
        
        
        if(tot2 == 0){
            sql = "insert into requisicion values(" + noR + "," + noO + ",'" + d + "','" + f + "'," + tot + "," + c1 + ",'" + d1 + "'," + cu1 + "," + ct1 + "," + c2 + ", null, " + cu2 + "," + tot2 + ", '" + unidad1 + "','" + unidad2  +"');";
        
        }else {
            sql = "insert into requisicion values(" + noR + "," + noO + ",'" + d + "','" + f + "'," + tot + "," + c1 + ",'" + d1 + "'," + cu1 + "," + ct1 + "," + c2 + ", '" + d2 + "'," + cu2 + "," + tot2 + ",'" + unidad1 + "','" + unidad2  +"');";
        }
 
        
        try {
            coneccion = conect.getConnection();
            statement = coneccion.createStatement();
    
            statement.addBatch(sql);
            statement.executeBatch();
    
            System.out.println("correcto");

        } catch (Exception e) { 
            System.out.println("El error es " + e);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cant1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cant1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequisicionM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequisicionM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequisicionM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequisicionM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequisicionM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tot;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton calcular;
    private javax.swing.JTextField cant1;
    private javax.swing.JTextField cant2;
    private javax.swing.JCheckBox cm1;
    private javax.swing.JCheckBox cm2;
    private javax.swing.JTextField costoTot1;
    private javax.swing.JTextField costoTot2;
    private javax.swing.JTextField costoU1;
    private javax.swing.JTextField costoU2;
    private javax.swing.JTextField descripcion1;
    private javax.swing.JTextField descripcion2;
    private javax.swing.JTextField fecha;
    private javax.swing.JCheckBox g1;
    private javax.swing.JCheckBox g2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox kg1;
    private javax.swing.JCheckBox kg2;
    private javax.swing.JCheckBox l1;
    private javax.swing.JCheckBox l2;
    private javax.swing.JCheckBox m1;
    private javax.swing.JCheckBox m2;
    private javax.swing.JCheckBox m21;
    private javax.swing.JCheckBox m22;
    private javax.swing.JCheckBox m31;
    private javax.swing.JCheckBox m32;
    private javax.swing.JCheckBox ml1;
    private javax.swing.JCheckBox ml2;
    private javax.swing.JTextField noOrden;
    private javax.swing.JTextField nomDepa;
    private javax.swing.JTextField nomRe;
    // End of variables declaration//GEN-END:variables
}
