/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sitemacosteoporordenes;

import sitemacosteoporordenes.Prosesos.VEstimacionDeTasaCIF;
import sitemacosteoporordenes.Prosesos.VHojasDeCosto;
import sitemacosteoporordenes.Prosesos.VRequisicionDeMateriales;
import sitemacosteoporordenes.Prosesos.VResumenDeTargetasDeTiempo;
/**
 *
 * @author monfi
 */
public class VentaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentaPrincipal
     */
    public VentaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPbackground = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jBRequicisioMateriales = new javax.swing.JButton();
        jBTarjetasTiempo = new javax.swing.JButton();
        jBEstimacionGIF = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBHojaCosto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPbackground.setBackground(new java.awt.Color(255, 245, 225));
        jPbackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(154, 107, 57));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jBRequicisioMateriales.setBackground(new java.awt.Color(154, 107, 57));
        jBRequicisioMateriales.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jBRequicisioMateriales.setForeground(new java.awt.Color(246, 214, 162));
        jBRequicisioMateriales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lista.png"))); // NOI18N
        jBRequicisioMateriales.setText("  Requicision de Materiales");
        jBRequicisioMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRequicisioMaterialesActionPerformed(evt);
            }
        });

        jBTarjetasTiempo.setBackground(new java.awt.Color(154, 107, 57));
        jBTarjetasTiempo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jBTarjetasTiempo.setForeground(new java.awt.Color(246, 214, 162));
        jBTarjetasTiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/despertador.png"))); // NOI18N
        jBTarjetasTiempo.setText("   Targetas de Tiempo     ");
        jBTarjetasTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTarjetasTiempoActionPerformed(evt);
            }
        });

        jBEstimacionGIF.setBackground(new java.awt.Color(154, 107, 57));
        jBEstimacionGIF.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jBEstimacionGIF.setForeground(new java.awt.Color(246, 214, 162));
        jBEstimacionGIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/insignia-porcentaje.png"))); // NOI18N
        jBEstimacionGIF.setText("   Estimacion Tasa GIF     ");
        jBEstimacionGIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEstimacionGIFActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 30, 30));
        jLabel1.setText("Inicio");

        jBHojaCosto.setBackground(new java.awt.Color(154, 107, 57));
        jBHojaCosto.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jBHojaCosto.setForeground(new java.awt.Color(246, 214, 162));
        jBHojaCosto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estadisticas.png"))); // NOI18N
        jBHojaCosto.setText("   Hoja de Costo                 ");
        jBHojaCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHojaCostoActionPerformed(evt);
            }
        });

        jPanel1.setForeground(new java.awt.Color(30, 30, 30));
        jPanel1.setPreferredSize(new java.awt.Dimension(170, 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBTarjetasTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBHojaCosto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jBEstimacionGIF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jBRequicisioMateriales)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jBRequicisioMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jBTarjetasTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jBEstimacionGIF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jBHojaCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jPbackground.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 608));

        jPanel3.setBackground(new java.awt.Color(108, 168, 244));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setText("Bienvenido");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPbackground.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 630, -1));

        jLabel3.setForeground(new java.awt.Color(28, 68, 132));
        jLabel3.setText("Colocar una introduccion al codigo");
        jPbackground.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 210, 20));

        jLabel4.setForeground(new java.awt.Color(28, 68, 132));
        jLabel4.setText("Recordar poner la letra a roboto");
        jPbackground.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(28, 68, 132));
        jLabel5.setText("Rob-Co Industries");
        jPbackground.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPbackground, javax.swing.GroupLayout.PREFERRED_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRequicisioMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRequicisioMaterialesActionPerformed
        // TODO add your handling code here:
        VRequisicionDeMateriales ventana = new VRequisicionDeMateriales();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBRequicisioMaterialesActionPerformed

    private void jBTarjetasTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTarjetasTiempoActionPerformed
        // TODO add your handling code here:
        VResumenDeTargetasDeTiempo ventana2 = new VResumenDeTargetasDeTiempo();
        ventana2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBTarjetasTiempoActionPerformed

    private void jBEstimacionGIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEstimacionGIFActionPerformed
        // TODO add your handling code here:
        VEstimacionDeTasaCIF ventana3 = new VEstimacionDeTasaCIF();
        ventana3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBEstimacionGIFActionPerformed

    private void jBHojaCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHojaCostoActionPerformed
        // TODO add your handling code here:
        VHojasDeCosto ventana4 = new VHojasDeCosto();
        ventana4.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBHojaCostoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEstimacionGIF;
    private javax.swing.JButton jBHojaCosto;
    private javax.swing.JButton jBRequicisioMateriales;
    private javax.swing.JButton jBTarjetasTiempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPbackground;
    // End of variables declaration//GEN-END:variables
}
